services:
  php:
    build:
      context: ./
    volumes:
      - ./:/var/www/html
    container_name: php_container_sf_test
    ports:
      - 8899:9000
    networks:
      - sf_test

  nginx:
    image: nginx
    container_name: nginx_container_sf_test
    ports:
      - 8999:80
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - sf_test

networks:
  sf_test:
    driver: bridge
